### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/flarum_ynh#11]
When I tried to install Flarum in the root directory of the domain "/", the server installs but redirect to the URL /flarum and returns a 404 error.

Thanks.

frju365

**Comment by tituspijean** [comment]
Hi,
I cannot reproduce the bug on a clean installation. However, it seems that there is no automatic redirection from http to https. Can you check that you are on https ?

**Comment by tituspijean** [comment]
Scratch that. It seems `assets` are called on https even if initial call was from http. Browsers don't like that and block these requests, leading to no css, no js, a broken forum.

I don't understand why you are redirected to `/flarum`. That should not happen. What's your `/etc/nginx/conf.d/.../flarum.conf` ?

**Comment by tituspijean** [comment]
[Solved](https://forum.yunohost.org/t/flarum-forum-package/1971/19), according to @frju365.
#12 may remain, though.
