### ISSUE TITLE
YNH | "...separate php ini file, merge your directives..." (if it is the source of the issue :)

### ISSUE THREAD

**Issue by jrd10** [YunoHost-Apps/flarum_ynh#116]
Hi, thank you for Flarum 
and making accessible from YUNOHOST.

I tried to install Flarum on YunoHost 3.6.4.3 (stable)
on a SSD2 OVH VPS 

- In English, public, Bazaar: Yes
- In French, public, Bazaar: Yes
- In Frecnh, publc, Bazaar: No (due the message below).

Your others recommendations OK.

All these installations failed. I noted:

> **Packagers ! Please do not use a separate php ini file, merge your directives in the pool file instead.**

Full log report and contest here : https://paste.yunohost.org/raw/amisomifag 
where I noted:
> Problem 1
> 2019-07-21 08:07:47,545: DEBUG -     - Installation request for flagrow/bazaar ^0.4.0 -> satisfiable by flagrow/bazaar[0.4.0].
> 2019-07-21 08:07:47,545: DEBUG -     - flagrow/bazaar 0.4.0 requires flarum/core ^0.1.0-beta.9 -> satisfiable by flarum/core[0.1.x-dev, v0.1.0-beta.9] but these conflict with your requirements or minimum-stability.

Thank you for your feedback.

Please, note too:
I understand, Flarum detected the issue an uninstalled what it has already installed.

Thank you again for Flarum
Jrd from France.

**Comment by tituspijean** [comment]
Hello, and thank you for your feedback.
The package was left unattended for months after Flarum's beta.8 release which broke its SSOwat companion extension.

The warning about `php.ini` file is only a warning, and is not related to the install-breaking error you quote right after. This one is about version requirements that are not matched. I am about to release a `testing` branch that hopefully fixes everything. Stay tuned!
