### ISSUE TITLE
SSO: authorized access

### ISSUE THREAD

**Issue by farvardin** [YunoHost-Apps/flarum_ynh#125]
**Describe the bug**
When administrating Flarum, for authorized access, by default it says "everyone". But SSO is not enabled for everyone in the yunohost database.

**Versions**
- YunoHost version: yunohost 3.6.4.6 (stable)
- Package version/branch: latest I've installed flarum from the latest github version: https://github.com/YunoHost-Apps/flarum_ynh

**To Reproduce**
- use yunohost administration panel. Access to the forum is to "all access". We can't login with SSO for existing users in the yunohost administration panel (but we can create new users in flarum). 
For being able to login with SSO, we have to enable users in the yunohost administration panel. Which is quite logical. But why having said "all access" before granting users, it's quite misleading.
When we add a user, it's written: "Utilisateurs autorisés:" with only the one we've added (but external users, outsite yunohost, can still use the forum).
Moreover, we can't remove access to users already added. When we click on "retirer les accès" (revoke access), we go back in the menu, but the access is still granted.

**Expected behavior**
- The yunohost administration panel shouldn't tell use all users can login if it's not the case with SSO. 
- we should be able to revoke the auth for a given user.

**Comment by tituspijean** [comment]
Is your forum set to public? If so, anyone can access the forum, visitors and any YNH users.

Right now the SSOwat extension does not check if a logged-in YNH user is actually allowed in the admin to access the app. I am not sure it can, actually. But if it is set to private, then that's the SSO's job to block access.

**Comment by farvardin** [comment]
yes, it's public. But when trying to access using ssowat, it didn't work for any YNH user, until we allow them to access individually in the ynh admin panel. I don't know if it's a bug or a limitation of ynh, but I found the message a bit confusing.

**Comment by tituspijean** [comment]
fb5098c8535c72057b924e8d91b050e210e84ecf should solve most of your issues. There was a bug in the ssowat extension that prevented registering new users. If set to public, any guest or YNH user can register/login.

However, there is indeed a bug on the admin panel. Like you, if I try to remove access to an user, I am sent back to the main menu, but the access has not been removed. I confirm the same behaviour with the app phpmyadmin.

**Comment by tituspijean** [comment]
Closing now, feel free to reopen if needed.
