### ISSUE TITLE
Yunohost Installation

### ISSUE THREAD

**Issue by bernalau** [YunoHost-Apps/flarum_ynh#13]
Hello. 

I try to install flarum on my yunohost server. 
I tried with Web Console and yunohost command line : each method failed to install...

I paste the log from command line installation : 

`Warning: Installing flarum/flarum (v0.1.0-beta.6)
Warning:   - Installing flarum/flarum (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning: Created project in .
Warning: Loading composer repositories with package information
Warning: Updating dependencies (including require-dev)
Warning:   - Installing symfony/process (v3.1.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/filesystem (v3.1.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing psr/log (1.0.2)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/polyfill-mbstring (v1.3.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/debug (v2.7.20)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/console (v2.8.13)
Warning:     Loading from cache
Warning:
Warning:   - Installing franzl/studio (0.11.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing tobscure/json-api (v0.3.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing nikic/fast-route (v0.6.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing psr/http-message (1.0.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing dflydev/fig-cookies (v1.0.2)
Warning:     Loading from cache
Warning:
Warning:   - Installing components/font-awesome (4.7.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing doctrine/lexer (v1.0.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing doctrine/inflector (v1.1.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing doctrine/collections (v1.3.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing doctrine/cache (v1.6.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing doctrine/annotations (v1.3.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing doctrine/common (v2.6.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing doctrine/dbal (v2.5.5)
Warning:     Loading from cache
Warning:
Warning:   - Installing zendframework/zend-diactoros (1.3.7)
Warning:     Loading from cache
Warning:
Warning:   - Installing filp/whoops (2.1.4)
Warning:     Loading from cache
Warning:
Warning:   - Installing franzl/whoops-middleware (0.4.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing danielstjules/stringy (1.10.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/contracts (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing paragonie/random_compat (v1.4.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/support (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/pipeline (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/bus (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/translation (v2.7.20)
Warning:     Loading from cache
Warning:
Warning:   - Installing nesbot/carbon (1.21.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/cache (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/finder (v2.7.20)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/filesystem (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/config (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/container (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/database (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/hashing (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing swiftmailer/swiftmailer (v5.4.3)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/mail (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/http-foundation (v2.7.20)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/validation (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/events (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing illuminate/view (v5.1.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing guzzlehttp/psr7 (1.3.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing intervention/image (2.3.8)
Warning:     Loading from cache
Warning:
Warning:   - Installing league/flysystem (1.0.32)
Warning:     Loading from cache
Warning:
Warning:   - Installing matthiasmullie/path-converter (1.0.8)
Warning:     Loading from cache
Warning:
Warning:   - Installing matthiasmullie/minify (1.3.41)
Warning:     Loading from cache
Warning:
Warning:   - Installing monolog/monolog (1.21.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing oyejorge/less.php (v1.7.0.10)
Warning:     Loading from cache
Warning:
Warning:   - Installing s9e/text-formatter (0.6.2)
Warning:     Loading from cache
Warning:
Warning:   - Installing symfony/yaml (v2.8.13)
Warning:     Loading from cache
Warning:
Warning:   - Installing http-interop/http-middleware (0.2.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing zendframework/zend-escaper (2.5.2)
Warning:     Loading from cache
Warning:
Warning:   - Installing zendframework/zend-stratigility (1.3.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing ircmaxell/security-lib (v1.1.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing ircmaxell/random-lib (v1.2.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing guzzlehttp/promises (1.2.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing tijsverkoyen/akismet (1.1.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing guzzlehttp/guzzle (6.2.2)
Warning:     Loading from cache
Warning:
Warning:   - Installing league/oauth2-client (1.4.2)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/core (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-flags (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-approval (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-akismet (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing league/oauth2-facebook (1.4.4)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-auth-facebook (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing league/oauth2-github (0.2.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-auth-github (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing league/oauth1-client (1.7.0)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-auth-twitter (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-bbcode (v0.1.0-beta.5)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-emoji (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-english (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-likes (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-lock (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-markdown (v0.1.0-beta.5)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-mentions (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing pusher/pusher-php-server (2.6.1)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-pusher (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-sticky (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-subscriptions (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-suspend (v0.1.0-beta.6)
Warning:     Loading from cache
Warning:
Warning:   - Installing flarum/flarum-ext-tags (v0.1.0-beta.7)
Warning:     Loading from cache
Warning:
Warning: symfony/console suggests installing symfony/event-dispatcher ()
Warning: filp/whoops suggests installing symfony/var-dumper (Pretty print complex values better with var-dumper available)
Warning: filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
Warning: paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
Warning: illuminate/support suggests installing jeremeamia/superclosure (Required to be able to serialize closures (~2.0).)
Warning: illuminate/support suggests installing symfony/var-dumper (Improves the dd function (2.7.*).)
Warning: symfony/translation suggests installing symfony/config ()
Warning: illuminate/cache suggests installing illuminate/redis (Required to use the redis cache driver (5.1.*).)
Warning: illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
Warning: illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
Warning: illuminate/database suggests installing fzaninotto/faker (Required to use the eloquent factory builder (~1.4).)
Warning: illuminate/database suggests installing illuminate/console (Required to use the database commands (5.1.*).)
Warning: illuminate/database suggests installing illuminate/pagination (Required to paginate the result set (5.1.*).)
Warning: illuminate/mail suggests installing aws/aws-sdk-php (Required to use the SES mail driver (~3.0).)
Warning: illuminate/mail suggests installing jeremeamia/superclosure (Required to be able to serialize closures (~2.0).)
Warning: intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Warning: league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
Warning: league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
Warning: league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
Warning: league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
Warning: league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
Warning: league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
Warning: league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
Warning: league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
Warning: league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
Warning: league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
Warning: league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
Warning: monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
Warning: monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
Warning: monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
Warning: monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
Warning: monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
Warning: monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
Warning: monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
Warning: monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
Warning: monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
Warning: monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
Warning: monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Warning: s9e/text-formatter suggests installing ext-xsl (Enables the XSLT renderer)
Warning: Writing lock file
Warning: Generating autoload files
Warning: sed: -e expression #1, char 20: unknown option to `s'
Error: Installation failed
`

Best Regards.

**Comment by bernalau** [comment]
I tryed on yunohost last version installed on debian 8.

**Comment by tituspijean** [comment]
@bernalau besides your email address, does any of your inputs contains a `@` ?

**Comment by tituspijean** [comment]
No answers since November, no one else seems to have this issue. Closing.
