### ISSUE TITLE
Upgrade fails to dpkg error

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/flarum_ynh#132]
**Describe the bug**
Upgrade fails, due to an error in the dpkg call of the script.
The previously backuped app stays is not set back, so page end up with "file not found" message.

**Versions**
- YunoHost version: 3.6.5.2
- Package version/branch: "latest"

**To Reproduce**
On an up-to-date server, run : 
```
    sudo yunohost app upgrade flarum
```

**Expected behavior**
Flarum app should upgrade to latest version.

**Logs**
The meaningful part of the operation log : 
```
Info: [######+.............] > Upgrading php-fpm configuration... [00h00m,00s]
Warning: dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
Warning: 
Warning: Type dpkg --help for help about installing and deinstalling packages [*];
Warning: Use 'apt' or 'aptitude' for user-friendly package management;
Warning: Type dpkg -Dhelp for a list of dpkg debug flag values;
Warning: Type dpkg --force-help for a list of forcing options;
Warning: Type dpkg-deb --help for help about manipulating *.deb files;
Warning: 
Warning: Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
Warning: Your requirements could not be resolved to an installable set of packages.
Warning: /usr/share/yunohost/helpers.d/logging: line 90: args_array: readonly variable
Error: Unable to upgrade flarum
```
I stay at your disposal to investigate :)

**Comment by tituspijean** [comment]
Hi,

If Flarum was actually at "latest" version, YunoHost wouldn't let you upgrade at all.
What is the version given by `yunohost app info flarum`?


I would like to know which variable passed to `dpkg` is empty.
Can you paste here the debug contents of the log? If you can't, try again with the `--debug` flag: run `yunohost app upgrade flarum --debug`.

**Comment by Jaxom99** [comment]
Sorry, I meant upgrade *to* latest. Actual version of flarum is "0.1.0-beta.7". Here is the debug log from the second upgrade attempt : https://paste.yunohost.org/raw/bidorigibe .

**Comment by tituspijean** [comment]
OK got it. I changed some setting keys at some point, and did not think about supporting older versions of the package. I am working on a fix.

**Comment by tituspijean** [comment]
This works on my test environment. Can you try the upgrade script available in `testing`?

```
yunohost app upgrade flarum -u https://github.com/YunoHost-Apps/flarum_ynh/tree/testing
```

*Assuming you have only one Flarum app, otherwise change* `flarum` *with the right id.*

**Comment by Jaxom99** [comment]
It worked ! App info returns ``version: 0.1.0-beta.10~ynh2``.
Many thanks for the quick fix 😉 Should I change something to next update ?

**Comment by tituspijean** [comment]
To go back to `master`, try `yunohost app upgrade flarum -u https://github.com/YunoHost-Apps/flarum_ynh`. It's a bit overkill only to change YunoHost's settings, but it should work.
