### ISSUE TITLE
[FR] Redirection error

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/flarum_ynh#142]
**Describe the bug**
Je viens juste d'installer Flarum, et ... 

> La page n’est pas redirigée correctement

> An error occurred during a connection to your.domain.tld.
> La cause de ce problème peut être la désactivation ou le refus des cookies.

PS: Les cookies sont activés.

**Versions**
- YunoHost version: 3.7
- Using, or trying to install package version/branch: master depuis le webmin

**To Reproduce**
Installer Flarum sur mon serveur, j'ai d'abord installé en sous-domaine, et quand j'ai vu l'erreur j'ai fait un change_url vers le domaine principal.

**Logs**
Installation : https://paste.yunohost.org/cowumekoku
Change URL : https://paste.yunohost.org/etukiduguw

**Comment by tituspijean** [comment]
Bug repoductible uniquement lors d'une tentative de connexion, tu confirmes ? La page d'accueil se charge bien sinon ?

**Comment by Aeris1One** [comment]
Tout le site était HS, pas de page d'accueil, mais apparemment c'était une incompatibilité avec Cloudflare (je l'utilise pour gérer mes nameserver, ils sont plus réactifs que ceux de Freenom). J'ai dû commenter les lignes de la config nginx qui redirigent http vers https et activer la redirection dans Cloudflare à la place.
