### ISSUE TITLE
404 on login or signup

### ISSUE THREAD

**Issue by nin0-0** [YunoHost-Apps/flarum_ynh#154]
After installation, I see 404 in the POST when trying to login or signup and it displays the error message `The requested resource was not found.`

The ssowat signin link gives 404 page. I have tried activating the ssowat plugin manually with composer but says nothing to be installed.

**Versions**
- YunoHost version: 4.0.8.2
- Using, or trying to install package version/branch: master -  0.1.0-beta.14~ynh1

**Logs**
Weirdly, no log files are generated in /var/log/flarum

**Comment by liberodark** [comment]
same for me. but is for all pages.

**Comment by tituspijean** [comment]
Hello,

I cannot reproduce this issue on YunoHost 4.0.8.3 and  Flarum 0.1.0-beta.14~ynh1 installed on a path.
Can you enable debugging in Flarum by setting the `debug` key to `true` in `/var/www/flarum/config.php`, line 2, and share the logs after triggering the error again?

The logs may be in `/var/www/flarum/storage/logs`. Have a look in `/var/log/nginx/YOURDOMAIN-error.log` too.

---

Edit: It seems to be happening when you install Flarum at the root of a domain, can you confirm this is your case?

**Comment by tituspijean** [comment]
Can you try the fix? 🤞 

`sudo yunohost app upgrade flarum -u https://github.com/YunoHost-Apps/flarum_ynh/tree/testing`

**Comment by nin0-0** [comment]
Working now !! :+1: 

Thanks a bunch

**Comment by nin0-0** [comment]
fixed
