### ISSUE TITLE
SSOwat login extension not working

### ISSUE THREAD

**Issue by jellium** [YunoHost-Apps/flarum_ynh#18]
This issue follows a [discussion on the YunoHost forum](https://forum.yunohost.org/t/flarum-forum-package/1971/49?u=jellium).

I successfully installed the flarum SSOwat extension with the following command:

`sudo -u www-data composer require tituspijean/flarum-ext-auth-ssowat:*@dev` 

and activated it in the Flarum extension panel.

After that, 
1) I cannot login directly from my YunoHost SSO authentication: I need to login manually in Flarum with my YnH login/password.
2) The `Login with SSOwat` button in the Flarum login popup brings me to a 404 error page, trying to reach: `https://domain.tld/yunohost/sso/?r=some 40 characters long hash`
3) When logged in and browsing the forum, I get the following error:
`Oops! Something went wrong. Please reload the page and try again.` associated with DEBUG verbose output untitled `200 OK` which contains the content I am trying to see, formatted with JSON notations (I think?)

Thanks!

**Comment by tituspijean** [comment]
Wrong repo, see [here](https://github.com/tituspijean/flarum-ext-auth-ssowat/issues/2).
