### ISSUE TITLE
PHP version does not allow to install any extensions

### ISSUE THREAD

**Issue by jschenke488** [YunoHost-Apps/flarum_ynh#192]
### Describe the bug

No matter what extension you try to install, this error appears
![image](https://user-images.githubusercontent.com/44783760/188658200-f82a47ef-4343-4a3a-addf-9b8e065efdb7.png)

### Context

- Hardware: VPS
- YunoHost version: 11.0.9.13
- I have access to my server: SSH, web admin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain: n/a
- Using, or trying to install package version/branch: 1.4.0~ynh1
- If upgrading, current package version: n/a

### Steps to reproduce

sudo -u flarum php7.3 composer.phar require [any extension]:"*"

**Comment by FullThrottle83** [comment]
Have you tried
sudo -u $app php7.4 composer.phar require vendor/extension

...it worked for me
