### ISSUE TITLE
Can't update to Flarum 1.5

### ISSUE THREAD

**Issue by FullThrottle83** [YunoHost-Apps/flarum_ynh#194]
Hey!

I try to update to Flarum 1.5 using instructions here.
Doesn't seem to work. Can this be tested on your end to out rule that it's my fault.
Thank you for your efforts!

**Edit**: My bad.
Had missed this part from Flarum doc.

- * Change the version strings of all bundled extensions (flarum/tags, flarum/mentions, flarum/likes, etc) in composer.json from ^0.1.0 to *.
- * Change flarum/core's version string in composer.json from ^0.1.0 to ^1.0.

Once I did that and ran this command:
sudo -u $app php7.4 composer.phar update --prefer-dist --no-plugins --no-dev -a --with-all-dependencies

Everything was updated to latest version :)

**Comment by tituspijean** [comment]
(Or just wait for the package to be updated, that's kinda its job 😛)

**Comment by FullThrottle83** [comment]
> (Or just wait for the package to be updated, that's kinda its job 😛)

Didn't know you'd update it so fast.
I'm new to Yunohost - It's awesome! :)
