### ISSUE TITLE
While trying install chat extension

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/flarum_ynh#198]
Hello, I encounter this issue while intending install extension, strange, no ?

`Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update xelson/flarum-ext-chat
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laminas/laminas-diactoros 2.17.0 requires php ^7.4 || ~8.0.0 || ~8.1.0 -> your php version (7.3.33) does not satisfy that requirement.
    - flarum/core v1.5.0 requires laminas/laminas-diactoros ^2.4.1 -> satisfiable by laminas/laminas-diactoros[2.17.0].
    - flarum/core is locked to version v1.5.0 and an update of this package was not requested.
`

**Comment by tituspijean** [comment]
What is the command you used to get this output?

(Code blocks are surrounded by triple backticks:  ```)

**Comment by tutle** [comment]
I was trying install [chat extension](https://discuss.flarum.org/d/25361-neon-chat-native-realtime-chat-applicaiton) according to this procedure
https://github.com/YunoHost-Apps/flarum_ynh#adding-extensions
What I used :
```
sudo su
app=flarum
cd /var/www/$app
sudo -u $app php7.3 composer.phar require xelson/flarum-ext-chat
```
same result with 
`.....require xelson/flarum-ext-chat:dev-master`

**Comment by tituspijean** [comment]
I had added a comment on the other issue: you need to use `php7.4`, the README is not up-to-date.

**Comment by tutle** [comment]
How can I know the php used ?
Dans webadmin/services, je n'ai que ça côté php
In webadmin/services, on have this with php
![image](https://user-images.githubusercontent.com/23037149/196034216-654d6ae7-b81c-46db-a95f-9d0904803a28.png)

**Comment by tituspijean** [comment]
`yunohost app info flarum -f | grep phpversion`

**Comment by tutle** [comment]
answer is `phpversion: 7.4`

**Comment by tutle** [comment]
It works !!! thanks a lot

**Comment by tutle** [comment]
It works !!! thanks a lot
