### ISSUE TITLE
How to find & install extensions for 1.7.1.?

### ISSUE THREAD

**Issue by KanenasPL** [YunoHost-Apps/flarum_ynh#216]
### Describe the bug

Once main code upgraded to 1.8.1, all files at Extiverse upgraded as well. Now, I can't install extensions (SSL method), as composer rejects files due to version incompatibility.
Where can I find extension files to install via SSL / Composer, matching 1.7.1 version?

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.3
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce
![Flarum_Screenshot_20230801_220703](https://github.com/YunoHost-Apps/flarum_ynh/assets/114858632/93d99190-caeb-46b9-b4f2-a8038933c612)

### Expected behavior

Installation succeeds

**Comment by tituspijean** [comment]
This is a composer / Flarum commands issue.
Since then, this package was upgraded to Flarum v1.8.1.
