### ISSUE TITLE
Fix installation on site subfolder

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/flarum_ynh#24]
Flarum on subfolder cannot be reached after #23.

**Comment by polytan02** [comment]
I think this bug should be fix by the use of .functions ?

https://github.com/polytan02/flarum_ynh/blob/patch-4/scripts/install#L40

**Comment by tituspijean** [comment]
Do you mean with the `path` slash detection ?

**Comment by tituspijean** [comment]
I think there is something else going on with this issue. The `path` is available, it is more about nginx's configuration. Here is the conf provided by Flarum, for a subdomain installation.

````
location / { try_files $uri $uri/ /index.php?$query_string; }
    location /api { try_files $uri $uri/ /api.php?$query_string; }
    location /admin { try_files $uri $uri/ /admin.php?$query_string; }

    location /flarum {
        deny all;
        return 404;
    }

    location ~* \.php$ {
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY ""; # Fix for https://httpoxy.org/ vulnerability
        fastcgi_index index.php;
    }
    
    location ~* \.html$ {
        expires -1;
    }

    location ~* \.(css|js|gif|jpe?g|png)$ {
        expires 1M;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    gzip on;
    gzip_http_version 1.1;
    gzip_vary on;
    gzip_comp_level 6;
    gzip_proxied any;
    gzip_types application/atom+xml
               application/javascript
               application/json
               application/vnd.ms-fontobject
               application/x-font-ttf
               application/x-web-app-manifest+json
               application/xhtml+xml
               application/xml
               font/opentype
               image/svg+xml
               image/x-icon
               text/css
               text/html
               text/plain
               text/xml;
    gzip_buffers 16 8k;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";
`````

On YunoHost, with a subfolder installation, we need to isolate this inside a `location /subfolder` block. As the `server` block does not provide a `root` instruction, it seems we have the play with `alias` inside the `location`, and subsequent nested `location`s.

**Comment by polytan02** [comment]
If you look at the PR "use of .functions" you will see that the upgrade of nginx was wrong in case of path=/

**Comment by polytan02** [comment]
This PR : https://github.com/YunoHost-Apps/flarum_ynh/pull/28/commits/4a5717daa3254735ce5fad96fe8fa0512ecd9eae

**Comment by tituspijean** [comment]
Yep, I was testing it while you were patching it. My bad for accepting the PR without testing ! (I have just discovered the `git fetch` for PRs... I'm learning good practice as I go along)

**Comment by polytan02** [comment]
No, it is fine.

It would be good to have only one nginx.conf in ../conf folder, it should make things easier ? 

Do I need to delete some PR I did ?

**Comment by tituspijean** [comment]
If you can manage to handle both cases with one `sed`ed file, that would be great.

I think we can override with your latest commits ?
