### ISSUE TITLE
Problème installation

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/flarum_ynh#36]
Il y a un problème apparemment dan l'installation, venant d'un utiliateur présent le 27/02/2017--- log : 
https://paste.abld.info/?a276431c028aa24d#kVw8z3lvxwwL4nLzT5oN3N2v0Jb1EB48pTsqlrKa+Zo=
https://paste.abld.info/?4b1544240c20cc1a#D+bUmPgQgOYIYmm6tQfYbklGHYcO6SC8pd/f/X8E2G8=

durée du pastebin : 6j.

**Comment by tituspijean** [comment]
Je suis justement en train de corriger des bugs dans l'installation. Je publie une MAJ dans la soirée. Tu me confirmeras si c'est corrigé.

**Comment by frju365** [comment]
Si tu as besoin d'aide, tu peux me parler sur le chat XMPP.

**Comment by tituspijean** [comment]
#37 pourrait résoudre ce problème.

**Comment by frju365** [comment]
Je pense que ça a résolu le problème. Je la réouvre si je m'apperçois que ce n'est pas le cas.
