### ISSUE TITLE
Composer removal

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/flarum_ynh#38]
On [`script/remove`](https://github.com/YunoHost-Apps/flarum_ynh/blob/master/scripts/remove#L16
) line 16, I don't think we should remove `composer`. We may encounter the case that other instances of Flarum are remain installed.

**Comment by frju365** [comment]
I agree with you. I had two instance of flarum on rpi and after removing one I did not find the composer software for the other instance. 
We can either let the software installed or delete it only if there is no other instance of flarum (with a condition)

**Comment by tituspijean** [comment]
I would vote to leave it be.

**Comment by frju365** [comment]
in fact for me it's an issue because I can't do update on the other instance if I haven't composer.

**Comment by tituspijean** [comment]
Oh I meant to leave composer installed. ;)
