### ISSUE TITLE
Flarum sur jenkins.

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/flarum_ynh#44]
Bonjour,
Comme le jenkins officiel est un peu occupé, j'ai décidé de créer un instance sur le jenkins du Groupe Apps :  https://jenkins-apps.nohost.me/jenkins/

Si l'app a besoin d'un test, on peut donc me demander ou demander à maxime.

**Comment by tituspijean** [comment]
@frju365
Je crois qu'il y a un problème sur le CI : https://ci-apps.yunohost.org/jenkins/job/flarum%20(Community)/lastFailedBuild/consoleFull
Le log de Flarum évoque plutôt une installation d'Etherpad.

**Comment by frju365** [comment]
Ok. J'ai rapporté le problème à Maniack et sur la chaîne Apps, on va voir si ça reproduit. Dans ce cas-là, on investiguera.
