### ISSUE TITLE
SSO module breaks api code handling

### ISSUE THREAD

**Issue by 20** [YunoHost-Apps/flarum_ynh#47]
Ayo people! Thx for your really nice application!

I've installed last yunohost on vanilla debian jessie.. 

Flarum seems to work but I've always to reload pages.. on first access I always get error "Oops! Something went wrong. Please reload the page" . With Debug = True I get no error (200 and json of the current page). No errors also on firebug or logs. Please help!

Have a look here: 
https://dpadua.mocambos.net/rodas/

**Comment by tituspijean** [comment]
Hi @20,
I couldn't replicate the error on first access, but after clicking around on several links it finally happened.
Can you provide an nginx error log ?

**Comment by 20** [comment]
Hi Titus! 

2017/04/03 01:30:53 [error] 823#0: *1235 FastCGI sent in stderr: "PHP message: PHP Deprecated:  The third argument to Zend\Stratigility\MiddlewarePipe() ($out) will be required starting with Stratigility version 2; please see https://docs.zendframework.com/zend-stratigility/migration/to-v2/ for more details on how to update your application to remove this message. in /var/www/flarum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php on line 101" while reading response header from upstream, client: 189.79.232.48, server: dpadua.mocambos.net, request: "GET /rodas/admin/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-flarum.sock:", host: "dpadua.mocambos.net", referrer: "https://dpadua.mocambos.net/rodas/"

**Comment by tituspijean** [comment]
Hi,
This warning is not related to your issue. Could you check that no other error precedes or follows this warning ? Also, can you check the acces.log ?

**Comment by frju365** [comment]
Hello,
Indeed, there i a problem due to the installation of SSO module. I will do a test Sunday but it could be much more good, if we can let the user choosing between having SSO or not (in that case, MySQL).
For me it doesn't work at all.
Thanks,
frju365

**Comment by tituspijean** [comment]
Confirmed on my side. Activating the SSO module leads to any returned api code to be processed as an error code.

**Comment by nixoye** [comment]
@tituspijean any update coming to this error?

**Comment by tituspijean** [comment]
The modifications brought by #54 circumvent this issue by removing the SSO module. To be fixed later.

**Comment by tituspijean** [comment]
Circumvented by #55. See the dedicated repository for debugging the extension.
