### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/flarum_ynh#49]
Hi,

Your app doesn't work for the moment.
It's fail on the installation tests on our CI.
https://ci-apps.yunohost.org/jenkins/job/flarum%20(Community)/11/consoleFull

Your app will be moved at 'notworking' status by the next week, on 15 of july.

**Comment by frju365** [comment]
ok. I close it. Status was alreadu set to Inprogress.
