### ISSUE TITLE
Utilisation de Version précise.

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/flarum_ynh#51]
Dans l'objectif d'avoir une maîtrise sur les version de flarum, il faudrait passer pluôt par des archive tar ou zip, car composer create installe la dernière version... mais le problème sera quand les voudront mettre à jour car le script ne saura pas quand mettre à jour.

**Comment by tituspijean** [comment]
Nous pouvons préciser une version en paramètre supplémentaire de `create-project`. Je pense qu'on peut s'en servir, et faire suivre le numéro de version de l'app.

**Comment by tituspijean** [comment]
Implémenté lors de l'installation par #55.
Restera à l'intégrer dans `upgrade` pour les prochaines versions, cf. #8.
