### ISSUE TITLE
Will updates continue?

### ISSUE THREAD

**Issue by nixoye** [YunoHost-Apps/flarum_ynh#52]
Love being able to manage Flarum on YunoHost. Will you continue to update the package?

**Comment by gamersalpha** [comment]
hope so, this project is dead ?

**Comment by frju365** [comment]
No, this project is not dead. but I'm wondering why there are more ppl complaining about that than ppl who contribute to the package. Strange, no ?

**Comment by frju365** [comment]
This issue is quite useless. On the flarum forum first, on the yuno-forum, and finally here.
