### ISSUE TITLE
Implement configuration file (automatic post-installation)

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/flarum_ynh#7]
Implement this feature : https://github.com/flarum/core/commit/7a8deb5f29cc3322e40741705dd0390dafbe1baf

**Comment by tituspijean** [comment]
Error during installation : 

```
thrown in /var/www/flarum/vendor/illuminate/container/Container.php on line 741
#6 {main}
#5 /var/www/flarum/flarum(18): Flarum\Console\Server->listen()
#4 /var/www/flarum/vendor/flarum/core/src/Console/Server.php(26): Flarum\Console\Server->getConsoleApplication()
#3 /var/www/flarum/vendor/flarum/core/src/Console/Server.php(52): Flarum\Foundation\Application->make('flarum.config')
#2 /var/www/flarum/vendor/flarum/core/src/Foundation/Application.php(486): Illuminate\Container\Container->make('flarum.config', Array)
#1 /var/www/flarum/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('flarum.config', Array)
#0 /var/www/flarum/vendor/illuminate/container/Container.php(741): ReflectionClass->__construct('flarum.config')
Stack trace:
PHP Fatal error: Uncaught exception 'ReflectionException' with message 'Class flarum.config does not exist' in /var/www/flarum/vendor/illuminate/container/Container.php:741
```

**Comment by tituspijean** [comment]
OK, my bad. Flarum/flarum is where the releases are put. Flarum/core is where development is happening. The commit by @opi that I was talking about is actually not released yet.

I will try to write a workaround, as beta6 is yet to be released.

**Comment by opi** [comment]
I don't know what happened with commit hash, but if you look at https://github.com/flarum/core/commit/e3c7f5379b5770aa397c30109bdce13c7bed7932, the configuration file installation  method should be shipped in beta5.

**Comment by tituspijean** [comment]
Oh you're right @opi. Meanwhile I found the problem ! https://github.com/flarum/core/commit/7192c4391bee006ccc2de3db6caa89803d72d130
By using the Server.php described in this commit, your install command works.
I'll add it in `/sources` as a workaround.

**Comment by tituspijean** [comment]
Solved with https://github.com/YunoHost-Apps/flarum_ynh/commit/99c86887531964b9c07f895d56043e47a3470831.

**Comment by opi** [comment]
nice !

**Comment by tituspijean** [comment]
Aaaaaaaaaaand beta6 was released earlier today. We can remove the workaround.

**Comment by tituspijean** [comment]
Done with https://github.com/YunoHost-Apps/flarum_ynh/commit/f9bb86956eb5f5fd087bc0c05209544a07aa4235.
