### ISSUE TITLE
Scripts timeout

### ISSUE THREAD

**Issue by romanocry** [YunoHost-Apps/flarum_ynh#74]
Bonjour,
Je viens d'installer ce package, via la GUI de YNH mais malheureusement, rien ne s'affiche lors du premier lancement ->HTTP ERROR 500
Nextcloud, Transmission, WordPress fonctionnent parfaitement dessus.
Serveur ARM, chez SoYouStart.
Il y a quelques chose a faire, après l'installation ?

Vous avez besoin de quoi comme logs pour debuger
Merci d'avance

**Comment by tituspijean** [comment]
Bonjour, pouvez-vous fournir le log de nginx juste après avoir généré l'erreur 500 ? Le fichier devrait être dans `/var/log/nginx/VOTRE-DOMAINE-error.log`.

Complément : je viens de réaliser une installation de mon côté, aucune erreur pour charger le site. Quels sont les paramètres que vous avez utilisé pour l'installation ?

**Comment by romanocry** [comment]
Je fournis le log dès que possible. 
J'ai juste rentré le lien github dans la GUI de YNH, section applications. Pas d'autre paramètres.

**Comment by tituspijean** [comment]
Flarum est disponible dans la liste des applications communautaires, que vous pouvez activer en appuyant sur le bouton vert sur la page listant les applications officielles dans l'adminstration.

Ce n'est pas possible de ne pas mettre de paramètres, si ce n'est ceux par défaut ? Avant l'installation, YNH vous demande le libellé, le domaine, le chemin, l'administrateur, le titre du forum, s'il est public et sa langue. (Vous pouvez omettre les informations sensible.)

**Comment by romanocry** [comment]
> Ce n'est pas possible de ne pas mettre de paramètres, si ce n'est ceux par défaut ? Avant l'installation, YNH vous demande le libellé, le domaine, le chemin, l'administrateur, le titre du forum, s'il est public et sa langue. (Vous pouvez omettre les informations sensible.)

Effectivement, ce sont des paramètres par défaut ;) J'ai donc laissé de base: 
Libéllé : Flarum ou Forum 
Domaine: l'adresse de chez SoYourStart: (pas encore de ndd) -> nsxxxxxxx.ip-xxx-xx-xx.eu 
Titre du forum: Forum de xxxx
Public: Oui
Langue: Fr

**Comment by romanocry** [comment]
Log
`2018/03/31 17:54:20 [error] 3466#0: *153 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/www/flarum/vendor/matthiasmullie/minify/src/Minify.php on line 318" while reading response header from upstream, client: 88.123.149.55, server: nsXXXXXXX.ip-XXX-XX-XX.eu, request: "GET /forum/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-flarum.sock:", host: "nsXXXXXXX.ip-XXX-XX-XX.eu"
`

**Comment by tituspijean** [comment]
Il semble qu'il y a un problème avec une dépendance de Flarum, un script est trop lent. Quelles sont les caractéristiques de votre SoYouStart, pour que je compare avec mon VPS ?

Tentez d'allouer plus de temps aux scripts php : `max_execution_time = 300` dans le `php.ini`.
Pour y accéder rapidement :
```
nano +372 /etc/php5/fpm/php.ini
```

**Comment by romanocry** [comment]
C'est un petit Serveur ARM-6T - Cortex A9 - 2GB
https://www.soyoustart.com/fr/offres/1801armada03.xml

edit: j'ai modifié le php.ini avec la valeur 300, reboot, mais tjs pareil :/

**Comment by tituspijean** [comment]
Ça devrait être largement suffisant pourtant. C'est un chouïa plus puissant qu'un RPi.

Y a-t-il un paramètre similaire, avec un timeout, dans `/etc/php5/fpm/pool.d/flarum.conf`? Je suis mobile ce soir, je ne peux vérifier moi-même.

**Comment by romanocry** [comment]
Oui, j'ai vu que ça tourné sur un RPi, donc normalement pas de problème de puissance... 
j'ai vu ça dans `/etc/php5/fpm/pool.d/flarum.conf`

> ; The timeout for serving a single request after which the worker process will
> ; be killed. This option should be used when the 'max_execution_time' ini option
> ; does not stop script execution for some reason. A value of '0' means 'off'.
> ; Available units: s(econds)(default), m(inutes), h(ours), or d(ays)
> ; Default Value: 0
> request_terminate_timeout = 600s
> 
> ; The timeout for serving a single request after which a PHP backtrace will be
> ; dumped to the 'slowlog' file. A value of '0s' means 'off'.
> ; Available units: s(econds)(default), m(inutes), h(ours), or d(ays)
> ; Default Value: 0
> request_slowlog_timeout = 5s

un peu plus loin

> Other common parameters
> php_value[max_execution_time] = 600
> php_value[max_input_time] = 600

**Comment by tituspijean** [comment]
J'avais déjà augmenté ces valeurs on dirait. L'erreur 500 apparaît instantanément ? Y a-t-il un fichier `/var/log/nginx/flarum.slow.log` ?

Pouvez-vous remontrer le log de Nginx après avoir mis la valeur à 300 ?

**Comment by romanocry** [comment]
Non c'est pas instantané, ça mouline 1min puis l'erreur apparaît. 

Il y a un fichier `/var/log/nginx/flarum.slow.log`

`
[01-Apr-2018 11:43:56]  [pool flarum] pid 11968
script_filename = /var/www/flarum//index.php
[0xb6616ed0] ArgString() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:2772
[0xb6616df0] ArgString() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:2784
[0xbe906830] ArgString() unknown:0
[0xb6616d20] array_map() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:2763
[0xb6616c80] ArgCache() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:2759
[0xb6616bb8] ObjCache() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:2744
[0xb6616ad0] NewObj6() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:2083
[0xb6616a18] parseRule() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:858
[0xb6616960] MatchFuncs() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:1009
[0xb66168b8] parsePrimary() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:1936
[0xb6616810] parseBlock() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:1991
[0xb6616768] parseRuleset() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:858
[0xb66166b0] MatchFuncs() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:1009
[0xb66165e0] parsePrimary() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:674
[0xb66164d8] GetRules() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:495
[0xb66163f0] parseFile() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Tree/Import.php:275
[0xb66162e8] ParseImport() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Tree/Import.php:198
[0xb6616210] compile() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Tree/Ruleset.php:248
[0xb6616140] evalImports() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Tree/Import.php:279
[0xb6616038] ParseImport() /var/www/flarum/vendor/oyejorge/less.php/lib/Less/Tree/Import.php:198
`

**Comment by tituspijean** [comment]
OK, normalement ça devrait mouliner 5 min au lieu d'une seule. Il y a un autre endroit où il y a un timeout de 60 secondes... J'ai l'impression que les "Other common parameters" ne sont pas pris en compte dans `pool.d/flarum.conf`. Modifions-les directement dans le `php.ini`. 

Ligne 382 du `php.ini`
```
nano +382 /etc/php5/fpm/php.ini
max_input_time = 600 (au lieu de 60)
```

Et évidemment `reboot` ou `service php5-fpm reload`.

**Comment by romanocry** [comment]
Pareil :( malheureusement :/ 
et ça mouline tjs entre 45 et 60 sec max...

**Comment by tituspijean** [comment]
Je me vois contraint de botter en touche. Je ne vois pas quel autre fichier de configuration pose problème. Je peux recommander un `apt-get update && apt-get upgrade`, sait-on jamais. Mais sinon, je ne sais pas d'où peut venir ce `timeout`.

**Comment by tituspijean** [comment]
Il est possible que le script `minify` soit appelé par la ligne de commande :
```
nano +382 /etc/php5/cli/php.ini
max_input_time = 600 (au lieu de 60)
```
Reboot et reteste

**Comment by romanocry** [comment]
pareil :( 
au bout de 70/75 sec d'attente ->erreur 500

**Comment by romanocry** [comment]
Est-ce que ça peux être le fait que je n'ai pas de ndd ?

**Comment by tituspijean** [comment]
Techniquement tu as bien un ndd, ce n'est pas ça le problème. Je crains que ça ne soit pas un problème lié à YNH.

Peux-tu tenter une installation manuelle de Flarum, en suivant les instructions de flarum.org ?

**Comment by romanocry** [comment]
J'ai plus l'install, mais a l'occas je testerais ;)
