### ISSUE TITLE
Can't open the admin panel

### ISSUE THREAD

**Issue by JanSeW** [YunoHost-Apps/flarum_ynh#76]
Hey, guys,
I installed Flarum for testing today. Unfortunately the admin panel does not seem to be available. The following error message appears:

![flarum_error](https://user-images.githubusercontent.com/16487822/39097678-d8c9dc82-465f-11e8-9360-c2cb9d228a4c.png)

I know Flarum installs itself automatically, but the admin panel should be accessible, right?
Flarum was installed over a subdomain, as you can see.

I hope you can help me.
Thxalot,
JanSe

**Comment by tituspijean** [comment]
Hi, for me to help you, can you provide a copy of the nginx error stating the 404 error ?
You should find it in `/var/log/nginx/YOUR_SUBDOMAIN.DOMAIN-error.log`.

**Comment by JanSeW** [comment]
Hey,

sorry for my late response.
Unfortunately the error log file is completely empty. In the meantime I
also tried a new installation, also without result.

Thxalot,
JanSe

Am Di., 24. Apr. 2018 um 17:39 Uhr schrieb Titus PiJean <
notifications@github.com>:

**Comment by tituspijean** [comment]
Confirmed, sort of.

- On my production server (OVH VPS 2016) : yes, /admin ends up with error 404.
- On my development environment (Yunohost docker) : no problem with the admin.

Any help is appreciated, I do not see why it behaves like that.

**Comment by tituspijean** [comment]
`server.org/flarum/admin` ➡️ 404
`server.org/flarum/admin/#/` (by manually adding `/#/`) ➡️  Success !

It seems to be related to `location` and `alias` directives acting up again. Maybe an update of Nginx caused this?

**Comment by antaeusdk** [comment]
Could one be a bit "naughty" and add that to the links after installation? I mean, adding /#/ 

It could be part of the clean up script.
