### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by 3615pipou** [YunoHost-Apps/flarum_ynh#78]
Yunohost 3
Debian 9
Raspberypi 3

When I install Flarum it makes all the apps crash including Flarum.
I mean i get a "502 Bad Gateway nginx" on all the apps using PHP.

Maybe it's a problem of PHP since Yunohost now use PHP7

I've been able to reproduce the error : it's realy when I install Flarum that then all the apps crash.

It's seems its because it makes php7.0-fpm crash

I'm not able to restart php7.0-fpm

> `systemctl start php7.0-fpm`
> Job for php7.0-fpm.service failed because the control process exited with error code.
> See "systemctl status php7.0-fpm.service" and "journalctl -xe" for details.
> 
> 
> 
> `systemctl status php7.0-fpm.service`
> Jul 04 17:28:26 YunoHost systemd[1]: Starting The PHP 7.0 FastCGI Process Manager...
> Jul 04 17:28:26 YunoHost php-fpm7.0[11164]: [04-Jul-2018 17:28:26] ERROR: [/etc/php/7.0/fpm/pool.d/flarum.conf:241] value is NULL for a ZEND_INI_PARSER_ENTRY
> Jul 04 17:28:26 YunoHost php-fpm7.0[11164]: [04-Jul-2018 17:28:26] ERROR: Unable to include /etc/php/7.0/fpm/pool.d/flarum.conf from /etc/php/7.0/fpm/php-fpm.conf at line 241
> Jul 04 17:28:26 YunoHost php-fpm7.0[11164]: [04-Jul-2018 17:28:26] ERROR: failed to load configuration file '/etc/php/7.0/fpm/php-fpm.conf'
> Jul 04 17:28:26 YunoHost php-fpm7.0[11164]: [04-Jul-2018 17:28:26] ERROR: FPM initialization failed
> Jul 04 17:28:26 YunoHost systemd[1]: php7.0-fpm.service: Main process exited, code=exited, status=78/n/a
> Jul 04 17:28:26 YunoHost systemd[1]: Failed to start The PHP 7.0 FastCGI Process Manager.
> Jul 04 17:28:26 YunoHost systemd[1]: php7.0-fpm.service: Unit entered failed state.
> Jul 04 17:28:26 YunoHost systemd[1]: php7.0-fpm.service: Failed with result 'exit-code'.

**Comment by alexAubin** [comment]
Indeed. I think that's related to the fact that the app was failing tests on stretch (maybe the php-fpm conf use stuff that are unavailable in php7). Thanks for the piece of log !

**Comment by tituspijean** [comment]
Oh, all the warning emails were put in my spam box, sorry ! I will investigate this, though I am a bit currently overwhelmed with the bugs in this app.
