### ISSUE TITLE
Better packaging - App level

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/flarum_ynh#8]
Upgrade script should be able to update `nginx`config, backup `mysql`and follow next update guidelines (something like [this](https://discuss.flarum.org/d/2352-flarum-v0-1-0-beta-5-released)).

**Comment by tituspijean** [comment]
We have to implement the new [YunoHost packaging guidelines](https://forum.yunohost.org/t/news-for-apps-packaging-automated-testing-procedure-to-make-an-application-official-new-quality-level-for-apps-and-standard-for-app-packaging/2399/3).

**Comment by tituspijean** [comment]
As of bcd145b, `package_check` returns : 

````Package linter: 			FAIL
Installation: 				SUCCESS
Suppression: 				SUCCESS
Installation en sous-dossier: 		SUCCESS
Suppression depuis sous-dossier: 	SUCCESS
Installation à la racine: 		FAIL
Suppression depuis racine: 		Not evaluated.
Upgrade: 				FAIL
Installation privée: 			FAIL
Installation publique: 			FAIL
Installation multi-instance: 		SUCCESS
Mauvais utilisateur: 			SUCCESS
Erreur de domaine: 			SUCCESS
Correction de path: 			SUCCESS
Port déjà utilisé: 			Not evaluated.
Backup: 				SUCCESS
Restore: 				FAIL
		    Notes de résultats: 9/15 - 12/20 :s
	   Ensemble de tests effectués: 15/21

Niveau de l'application: 1
	   Niveau 1: 1
	   Niveau 2: 0
	   Niveau 3: 0
	   Niveau 4: 1
	   Niveau 5: 0
	   Niveau 6: 0
	   Niveau 7: 0
	   Niveau 8: 0
	   Niveau 9: 0
	   Niveau 10: 0
````

- Manual root install is OK.
- Upgrading fails : to be investigated.
- Private and public installs are actually OK, according to detailed log.
- False positive on `/check-2` multi-instance with `/check`. Won't be solvable until Nginx's debug. (See https://github.com/YunoHost-Apps/flarum_ynh/pull/37#issue-210562505)
- Restoring fails : no `sudo` with `mkdir -p /opt/flarum_composer`

We would score 13/15.

**Comment by frju365** [comment]
Je pense que l'erreur à la racine est une erreur du test... je vais travailler sur le restore demain. Il faudrait tout de même indiquer l'état de l'application dans le README afin de ne plus tromper l'utilisateur. (contairement à  cette aprè-midi)

**Comment by tituspijean** [comment]
The `package_check` log is [here](https://paste.yunohost.org/asokunozip.xml).

**Comment by tituspijean** [comment]
As of d059d5e8439fed02e86b355518351b9dcd43e6d8, `package_check` gives

```
Package linter:                  SUCCESS
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      SUCCESS
Deleting from a sub path:        SUCCESS
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         Not evaluated.
Installation in private mode:    SUCCESS
Installation in public mode:     SUCCESS
Multi-instance installations:    SUCCESS
Malformed path:                  SUCCESS
Port already used:               Not evaluated.
Backup:                          SUCCESS
Restore:                         SUCCESS
Change URL:                      Not evaluated.
Level of this application: 2 (Installable in all situations)
	   Level 1: 1
	   Level 2: 1
	   Level 3: 0
	   Level 4: 0
	   Level 5: 1
	   Level 6: 1
	   Level 7: 1
	   Level 8: 0
	   Level 9: 0
	   Level 10: 0
```

Full log [here](https://paste.yunohost.org/igiviheras.coffeescript).
I disabled Upgrade check: even though the script is functional, I have not figured out how to handle the version numbers of Flarum beta.
Level 4 is partially reached, #64 has to be implemented.

**Comment by tituspijean** [comment]
As of b84531d7a99c9889afc46ea52c8a14043dc85c9b, `package_check` gives

```
Package linter:                  SUCCESS
Installation:                    SUCCESS
Deleting:                        SUCCESS
Installation in a sub path:      SUCCESS
Deleting from a sub path:        SUCCESS
Installation on the root:        SUCCESS
Deleting from root:              SUCCESS
Upgrade:                         SUCCESS
Installation in private mode:    SUCCESS
Installation in public mode:     SUCCESS
Multi-instance installations:    SUCCESS
Malformed path:                  SUCCESS
Port already used:               Not evaluated.
Backup:                          SUCCESS
Restore:                         SUCCESS
Change URL:                      Not evaluated.
Level of this application: 7 (Successfully pass functional tests)
	   Level 1: 1
	   Level 2: 1
	   Level 3: 1
	   Level 4: 1
	   Level 5: 1
	   Level 6: 1
	   Level 7: 1
	   Level 8: 0
	   Level 9: 0
	   Level 10: 0
```

Full log [here](https://paste.yunohost.org/ipetijepib.coffeescript).
**Level 7 is reached.**

**For level 8**

- YEP 2.18.5 is being discussed on #65 : I would prefer not to make the YNH tile overlay the forum
- YEP 3.4 has been implemented by moving `composer` back into the `$final_path` in #61  🆗 
- other required YEPs 🆗 

**For level 9**

- YEP 2.17 is being discussed in #67 
- YEP 4.2.1 is being discussed in #69

**Comment by tituspijean** [comment]
[Full log](https://paste.yunohost.org/uzotociqar.coffeescript) from e8af9ef06720a9188bccc82da8573598eb25fe7b: still level 7.

**Comment by tituspijean** [comment]
App stable at level 7, closing.

**Comment by frju365** [comment]
NICE ! :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
:smiley: :smiley: :smiley: :smiley: :smiley: :smiley: :smiley:
