### ISSUE TITLE
Question : Title, an option ?

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/flarum_ynh#90]
Why title is optional ? Because if the package is stable, we could set is as needed.

**Comment by tituspijean** [comment]
It was initially a way for me to test the package with or without the automatic post-installation.

We can definitely set it as required now, it will smoothen the UX.

**Comment by tituspijean** [comment]
Should we leave the `if` clause before the post-installation as is? If the system correctly enforces the new required field, this test for empty variables is useless.
https://github.com/YunoHost-Apps/flarum_ynh/blob/deb373cb1111d4dd88b882d9492da88141a9defc/scripts/install#L176

To do: at least rephrase the comments below the `if`.

**Comment by frju365** [comment]
mh... yes this condition is useless now.
